### ISSUE TITLE
Into<T> for String when T has a fn(String) -> T, Secret types don't have a Into impl

### ISSUE THREAD

**Issue by Emilgardis** [ramosbugs/oauth2-rs#112]
Is there a reason why `AccessToken`, `RefreshToken`, `ClientSecret`, etc (basically all new_secret_type! types) don't have a `Into` implementation? If not, it'd be nice to have :)

Minor sidenote, why `Into` and not `From`?

**Comment by ramosbugs** [comment]
> Is there a reason why `AccessToken`, `RefreshToken`, `ClientSecret`, etc (basically all new_secret_type! types) don't have a `Into` implementation? If not, it'd be nice to have :)

Great question, I left `Into<T> for String` unimplemented for secrets for similar reasons as #107. If the types can be coerced trivially to strings, it's a lot easier for users to shoot themselves in the foot. Instead, the API adds an explicit `secret()` method so that it's clear in the code that a sensitive secret is being used. This also makes it easier for security teams to grep for/audit secret usage. I do this for all secrets :-)

> Minor sidenote, why `Into` and not `From`?

at least back when I wrote that code, Rust didn't allow implementing a foreign trait (`From<T>`) on a foreign type (`String`). I think `Into` is the only option for that situation, but I wouldn't be surprised if that's been addressed by some RFC.

**Comment by Emilgardis** [comment]
Thanks for the answer!

However, what I'm asking for is to enable this usage

```rust
fn uses_secret(client_secret: impl Into<ClientSecret>) { 
    let secret: ClientSecret = client_secret.into();
    // do stuff...
}

uses_secret("myvalidsecret".to_string())

```

I fully understand why I cant trivially extract the underlying data of a secret without being explicit, what I'm asking for is being able to trivially create a secret when the data is already represented as a String.

**Comment by Emilgardis** [comment]
Ping @ramosbugs 

I think this should be implemented, this is not a feature request to go from secret -> string, but string->secret. Does that carry any security or vetting burdens?

**Comment by ramosbugs** [comment]
ah, that's a different question. none of the NewTypes in this crate implement traits to construct them, including the non-secrets (e.g., https://docs.rs/oauth2/4.0.0-alpha.1/oauth2/struct.ClientId.html). The non-secrets implement `Into` to convert from the NewType *to* the underlying string (e.g., `ClientId::into()` gives you a `String`), but none of them implement traits to construct an object *from* a string.

the reason that's omitted isn't for security; it's because it makes NewTypes far less useful. aside from automatic redaction for the secret types, the main reason for the NewType pattern is to prevent bugs caused by, e.g., passing function arguments in the wrong order. "stringly typed" code is prone to these sorts of bugs since the compiler doesn't understand the difference between different string arguments. this makes it harder to refactor code (which may add or reorder function arguments) without introducing bugs.

using distinct types (NewTypes) to represent different types of data makes these bugs less likely since it becomes a compiler error if you try to pass a `ClientId` where a `RedirectUrl` is expected. implementing `From<String>` on these types would enable code that looks like `foo("bar".into(), "baz".into())`, which is basically just stringly-typed code. instead, this crate's APIs are designed to encourage code that looks like `foo(SomeType::new("bar".to_string()), SomeOtherType::new("baz".to_string()))`, which makes it explicit which types are being passed in, and it allows the compiler to enforce the correctness of these types. some other languages (e.g., Python, Scala) solve this problem with named arguments, but Rust doesn't support those. its main tool for this is types.

this approach is certainly more verbose than using `From<String>`, but I feel it's more inline with the Rust ethos of building misuse-resistant interfaces.
