### ISSUE TITLE
Pinned unicode-normalization =0.1.9 dependency incompatible with publicsuffix v1.5.6

### ISSUE THREAD

**Issue by kpcyrd** [ramosbugs/oauth2-rs#130]
I have a dependency on publicsuffix:
```
publicsuffix v1.5.6 depends on ->
idna v0.2.2 depends on ->
unicode-normalization ^0.1.17
```
And I also have a dependency on oauth2 v3.0.0:
```
oauth2 v3.0.0 depends on ->
unicode-normalization v0.1.9
```
This breaks tools like `cargo outdated` because `0.1.9` doesn't match `^0.1.17`.

**Comment by ramosbugs** [comment]
it looks like I pinned to this version awhile back in 5042753669f5357473460bfbed42742d57e26480 in order to continue supporting any version of Rust >= 1.34.0. Newer versions of `unicode-normalization` don't compile with older versions of Rust. While I don't think supporting a version as ancient as 1.34.0 is particularly important in 2021, I'm hesitant to change the MSRV of the current stable release.

there are a couple of options:
1. upgrade to the latest 4.0.0 alpha release, which has a MSRV of 1.45.0 and doesn't currently pin to any exact crate versions. the "alpha" name mainly indicates that future breaking changes are possible, but all of these versions should be safe to use in production (which I do!).
2. we can prepare a 3.1.0 release that raises the MSRV of the 3.x release and pulls in newer packages. this might involve some effort since CI breaks every few weeks for a given MSRV (due to downstream dependencies using newer language features) unless I check in a frozen `Cargo.lock` for CI to use.

**Comment by ramosbugs** [comment]
This should no longer be an issue in recent releases. Please feel free to reopen if that's not the case.
