### ISSUE TITLE
'naive redirect server' improvement?

### ISSUE THREAD

**Issue by nyvs** [ramosbugs/oauth2-rs#157]
I've seen that the redirect server in the google oauth example is labeled as a 'naive' approach and I am wondering what needs to be done to make it a less naive, better approach?

For me _naive_ implies that there are obviously way better approaches, so I am just curious what an improvement could be :)

**Comment by ramosbugs** [comment]
hey @nyvs,

I'd suggest using a more robust HTTP server such as `rocket`, `warp`, or `actix-web` rather than directly serving TCP connections as `examples/google.rs` does. Those frameworks all provide lots of important features for production web servers (concurrency, request/response marshaling, logging, etc.).

As for the OAuth2 code (redirect) flow itself, here's a useful reference covering some security best practices: https://tools.ietf.org/id/draft-ietf-oauth-security-topics-13.html#rec_redirect

**Comment by nyvs** [comment]
Thank you for your quick answer. This leads me to a breaktrough in my thinking actually. As my app consists of **client** and **server**, I could just set the redirect url to the server (which uses `rocket` already 👍🏻 )
