### ISSUE TITLE
how can i get github user data in oauth2?

### ISSUE THREAD

**Issue by lpf763827726** [ramosbugs/oauth2-rs#161]
i try to copy and use in my code, but i don't know how can i get the user data(like username, email...)

**Comment by lpf763827726** [comment]
i even try to use `&scopes[0]` or `.get(0).unwrap()`, but they just return that name

my following token returned:
```
Ok(StandardTokenResponse { access_token: AccessToken([redacted]), token_type: Bearer, expires_in: None, refresh_token: None, scopes: Some([Scope("public_repo,user")]), extra_fields: EmptyExtraTokenFields })
```

**Comment by ramosbugs** [comment]
the OAuth2 flow only authenticates the user and returns an access token. once you have an access token, you'll then need to use it to make further requests to the GitHub API in order to perform operations such as getting the user's info (i.e., [ `GET /user`](https://docs.github.com/en/rest/reference/users)). GitHub provides lots of documentation about their APIs, which are beyond the scope of OAuth2 and this crate.

some potentially useful crates (which I haven't evaluated) that provide GitHub API access in Rust:
- [octocrab](https://crates.io/crates/octocrab)
- [hubcaps](https://crates.io/crates/hubcaps)

if neither of those work for you, you can make HTTP requests directly to the GitHub APIs using one of the popular HTTP client crates such as `reqwest` or `surf`.

**Comment by lpf763827726** [comment]
ok, thanks for answer, i will try it how to get the data, i always thought there would be some built-in methods to get
