### ISSUE TITLE
consider replacing `chrono` with `time`

### ISSUE THREAD

**Issue by ctaggart** [ramosbugs/oauth2-rs#177]
Please consider replacing `chrono` with `time`.

https://github.com/ramosbugs/oauth2-rs/blob/23f06d6acd644c1ec294baf95f0d211ed4f044a9/Cargo.toml#L34

Many other projects have made the switch this year. A good example is:

- https://github.com/dermesser/yup-oauth2/pull/172/files

**Comment by ramosbugs** [comment]
This would introduce a breaking change, unfortunately, due to `chrono::DateTime` being used in [`TokenIntrospectionResponse`](https://docs.rs/oauth2/4.2.2/oauth2/trait.TokenIntrospectionResponse.html), [`DeviceAccessTokenRequest::set_time_fn`](https://docs.rs/oauth2/4.2.2/oauth2/struct.DeviceAccessTokenRequest.html#method.set_time_fn), and potentially elsewhere. It will also increase the MSRV. I think it'll make sense to do this alongside other future breaking changes, but I don't think it's worth a new major version on its own since the functionality used by this library isn't affected by the RUSTSEC vulnerabilities that get flagged.

See related discussion in ramosbugs/openidconnect-rs#74.

**Comment by ramosbugs** [comment]
The `openidconnect` crate is open for breaking changes again due to needing to bump its MSRV to 1.57, and I think this would be a good opportunity for the `oauth2` crate to follow suit.

Now that `chrono` is being maintained again, it's not super clear to me which of the crates would be preferable to use. In either case, both `oauth2` and `openidconnect` will need to expose both date/time and duration types via its public API that will couple it with a specific major version of `chrono`/`time` since there's no std type for representing dates.

If folks have opinions, please share them :-)
