### ISSUE TITLE
Compounding the sleep intervals if there is an error in the http_client

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#214]
https://github.com/ramosbugs/oauth2-rs/blame/00fa30b336a8b3c9c4c900ae3ccba371459c0ac8/src/lib.rs#L2435

It was observed that the sleep interval if there is an error in the http_client is compounding. Bad for user experience, it will wait them too long to get the token example if ethernet cable is unplugged for a long time, then plugged it again and login in their cloud account. How about just doubling it but not compounding?

**Comment by LorenzoLeonardo** [comment]
Here is the pull request I made to fix the issue of compounding.
https://github.com/ramosbugs/oauth2-rs/pull/215

**Comment by ramosbugs** [comment]
Hmm... the [relevant part of the spec](https://www.rfc-editor.org/rfc/rfc8628#section-3.5) here is:
>  On encountering a connection timeout, clients MUST unilaterally
   reduce their polling frequency before retrying.  The use of an
   exponential backoff algorithm to achieve this, such as doubling the
   polling interval on each such connection timeout, is RECOMMENDED.

A connection timeout seems similar to the `slow_down` case except where the server is so overloaded it can't process the request and return `slow_down`. For `slow_down`, the spec says:
>  A variant of "authorization_pending", the authorization request is
      still pending and polling should continue, but the interval MUST
      be increased by 5 seconds for this and all subsequent requests.

I think it's reasonable to set an upper bound on the polling interval so that it doesn't double to an effectively infinite backoff in the scenario you're describing, but some backoff is explicitly required by the spec. Unfortunately, the generic `http_client` interface's error type doesn't provide us a way to distinguish connection timeouts from other types of request errors. A disconnected ethernet cable would probably result in a harder error than a timeout since, e.g., DNS resolution would potentially fail.

I propose we leave the doubling logic but set a default upper bound to 10 seconds (twice the default 5-second interval mentioned throughout the spec). It's potentially also worth adding a `set_max_backoff_interval` method to `DeviceAccessTokenRequest` so that clients can override the 10-second default behavior.

For clarity, I'm proposing changing this:
https://github.com/ramosbugs/oauth2-rs/blob/00fa30b336a8b3c9c4c900ae3ccba371459c0ac8/src/lib.rs#L2436-L2437
to something like:
```rust
// RFC 8628 requires a backoff in cases of connection timeout, but we can't
// distinguish between connection timeouts and other HTTP client request errors
// here. Set a maximum backoff so that the client doesn't effectively backoff
// infinitely when there are network issues unrelated to server load.
let new_interval = std::cmp::min(
    current_interval.checked_mul(2).unwrap_or(current_interval),
    self.max_backoff_interval.unwrap_or(DEFAULT_MAX_BACKOFF_INTERVAL),
);
```

**Comment by LorenzoLeonardo** [comment]
> Hmm... the [relevant part of the spec](https://www.rfc-editor.org/rfc/rfc8628#section-3.5) here is:
> 
> > On encountering a connection timeout, clients MUST unilaterally
> > reduce their polling frequency before retrying.  The use of an
> > exponential backoff algorithm to achieve this, such as doubling the
> > polling interval on each such connection timeout, is RECOMMENDED.
> 
> A connection timeout seems similar to the `slow_down` case except where the server is so overloaded it can't process the request and return `slow_down`. For `slow_down`, the spec says:
> 
> > A variant of "authorization_pending", the authorization request is
> > still pending and polling should continue, but the interval MUST
> > be increased by 5 seconds for this and all subsequent requests.
> 
> I think it's reasonable to set an upper bound on the polling interval so that it doesn't double to an effectively infinite backoff in the scenario you're describing, but some backoff is explicitly required by the spec. Unfortunately, the generic `http_client` interface's error type doesn't provide us a way to distinguish connection timeouts from other types of request errors. A disconnected ethernet cable would probably result in a harder error than a timeout since, e.g., DNS resolution would potentially fail.
> 
> I propose we leave the doubling logic but set a default upper bound to 10 seconds (twice the default 5-second interval mentioned throughout the spec). It's potentially also worth adding a `set_max_backoff_interval` method to `DeviceAccessTokenRequest` so that clients can override the 10-second default behavior.
> 
> For clarity, I'm proposing changing this:
> 
> https://github.com/ramosbugs/oauth2-rs/blob/00fa30b336a8b3c9c4c900ae3ccba371459c0ac8/src/lib.rs#L2436-L2437
> 
> 
> to something like:
> ```rust
> // RFC 8628 requires a backoff in cases of connection timeout, but we can't
> // distinguish between connection timeouts and other HTTP client request errors
> // here. Set a maximum backoff so that the client doesn't effectively backoff
> // infinitely when there are network issues unrelated to server load.
> let new_interval = std::cmp::min(
>     current_interval.checked_mul(2).unwrap_or(current_interval),
>     self.max_backoff_interval.unwrap_or(DEFAULT_MAX_BACKOFF_INTERVAL),
> );
> ```

Kindly check this pull request regarding this change. https://github.com/ramosbugs/oauth2-rs/pull/216
