### ISSUE TITLE
How do I track state-pkce_verifier pairs for each authorization flow?

### ISSUE THREAD

**Issue by stephen-ulmer** [ramosbugs/oauth2-rs#224]
First, thanks for you contributions to the community.

In the example, the same pkce challenge and verifier pair would be reused across authorization flows. Is this the correct implementation?

It seems like they should be generated for each authorization flow, then the state and pkce verifier should be stored for the code exchange on callback, but the secret types make it hard to persist the token and verifier as strings in a dataabase.

Am I misunderstanding?

**Comment by ramosbugs** [comment]
> In the example, the same pkce challenge and verifier pair would be reused across authorization flows. Is this the correct implementation?

Definitely do not reuse the CSRF `state` or PKCE challenge across multiple auth flows! Their security depends on attackers not being able to guess the values, which becomes trivial if they're reused.

How best to manage these parameters during the flow depends on the structure of the application and whether it's able to hold state. The examples could do a better job of demonstrating best practices there, but it's unclear how to do that since applications use different types of storage and session management/cookies.

> the secret types make it hard to persist the token and verifier as strings in a dataabase.

If your application is stateful, it's fine to store these values in a DB. You can always access the secret string value by calling the `.secret()` method on these types, and they implement `Serialize/Deserialize`. They don't implement `Display` to avoid accidentally logging secrets.

If you do store these values in a DB, keep in mind that you really only need a hash or HMAC of the `state` in order to verify that the redirect from the authorization server includes the correct state (just verify that the hash/HMAC of that `state` matches what you've stored). That means that even if the contents of your DB leak, the `state` can't be guessed without brute forcing it from the hash/HMAC. These flows are short-lived, so this isn't that critical, but it's a best practice.

A stateless alternative is to store the CSRF `state` on the client using a cookie. This is conceptually similar to [double-submit cookies](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie) used for general CSRF protection.

**Comment by stephen-ulmer** [comment]
Thank you so much for the thorough response!

Sorry I missed `.secret()`!!
