### ISSUE TITLE
Dealing with apis which don't include token_type in response

### ISSUE THREAD

**Issue by jiftoo** [ramosbugs/oauth2-rs#234]
Hello. I'm adding oauth support to my app and one of the endpoints only sends the access_token and expires_in during code exchange. This causes exchange_code to return a serde error. Is there a graceful way to circumvent this? My current solution is to deserialize the response of async_http_client inside request_async, add the missing field manually and serialize again. Making a custom type which implements TokenType doesn't seem to be an option because of serde attributes in the definition of StandardTokenResponse.

**Comment by ramosbugs** [comment]
Hey @jiftoo,

Unfortunately, `token_type` is a [required](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2) field in the OAuth2 spec.

Two workarounds come to mind:
1. Implement a request shim that rewrites the response to be spec-compliant (which it sounds like you're currently doing).
2. Define your own struct that implements the [`TokenResponse`](https://docs.rs/oauth2/latest/oauth2/trait.TokenResponse.html) trait rather than using `StandardTokenResponse` (which, as the name implies, expects the response to adhere to the RFC 6749 standard). You can omit the `token_type` field from the underlying struct but still implement the required `token_type` trait method to return the appropriate `BasicTokenType` enum variant. If that enum doesn't satisfy your use case, you can also define your own enum (which must implement the `TokenType` marker trait).

Hope that helps!

**Comment by jiftoo** [comment]
Hi, thanks for responding!

If `token_type` is a required field in the RFC then clearly there's nothing to be done. I'll stick with my current workaround for now.
