### ISSUE TITLE
Future is not Send

### ISSUE THREAD

**Issue by LorenzoLeonardo** [ramosbugs/oauth2-rs#255]
![image](https://github.com/ramosbugs/oauth2-rs/assets/97872577/c3f6aecb-9054-4d74-a555-2f8f1ca432d1)

I have encountered this error, I created a trait in my application so that it would be mockable during the test, but I encountered this error. Let me know what I lack.

**Comment by LorenzoLeonardo** [comment]
My goal is to create a mockable AsyncHttpClient and a production AsyncHttpClient

**Comment by LorenzoLeonardo** [comment]
Suggesting to put + Send here

```
impl<'c> AsyncHttpClient<'c> for Curl {
    type Error = Error<Collector>;

    fn call(
        &'c self,
        request: HttpRequest,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<HttpResponse, Self::Error>> + 'c + Send>>
    {
        Box::pin(self.send(request))
    }
}
```

**Comment by LorenzoLeonardo** [comment]
PR -> https://github.com/ramosbugs/oauth2-rs/pull/256

**Comment by ramosbugs** [comment]
Hmm this is tricky because the future `reqwest` returns isn't `Send` or `Sync`: https://docs.rs/reqwest/latest/reqwest/struct.Client.html#method.execute.

Note that the 4.x interface also didn't have `Send` or `Sync` bounds on the returned future (`F: Future<Output = Result<HttpResponse, RE>>`): https://docs.rs/oauth2/latest/oauth2/struct.DeviceAuthorizationRequest.html#method.request_async

It looks like `async_trait` adds `Send` bounds by default: https://docs.rs/async-trait/latest/async_trait/#non-threadsafe-futures

Does using `#[async_trait(?Send)]` on your `DeviceCodeFlowTrait` as described [here](https://docs.rs/async-trait/latest/async_trait/#non-threadsafe-futures) work?

**Comment by LorenzoLeonardo** [comment]
Hello David

It is now working using #[async_trait(?Send)]. Thanks
