### ISSUE TITLE
Arbitrary parameters in requests and responses.

### ISSUE THREAD

**Issue by andor44** [ramosbugs/oauth2-rs#27]
In 8.2 the spec allows for adding arbitrary, vendor-specific (or as described in 11.2, getting them registered) parameters for both requests and responses. As an example, in my case I'm working with OIDC, which is built on top of OAuth2, which makes use of this by using an extra `id_token` field in the response for a JWT token. Would providing support for extra fields (not OIDC support itself) be in the scope of this library?

In Go everything unknown is stored into an [untyped field](https://github.com/golang/oauth2/blob/a032972e28060ca4f5644acffae3dfc268cc09db/token.go#L54) that the user can [retrieve](https://github.com/golang/oauth2/blob/a032972e28060ca4f5644acffae3dfc268cc09db/token.go#L96).

I made a quick and dirty implementation of the above approach in [here](https://github.com/andor44/oauth2-rs/tree/extra_token_fields) which works for me, but this doesn't yet support *truly* arbitrary fields, only string fields. If there's interest in it here I can flesh this out.

**Comment by ramosbugs** [comment]
@andor44: I'm looking at integrating with OIDC in Rust as well, so I'd definitely be interested. Since Rust is all about static typing, I wonder if it would be possible to use generics to solve this problem. Perhaps `Token` could become a `trait` with the minimum required fields, and callers can supply their own implementations of that trait with additional fields relevant to their use case? I'm not sure if serde would support anything like this.

@alexcrichton: would this be something you'd be interested in? I'm happy to help with the effort. Some form of [OIDC](http://openid.net/specs/openid-connect-core-1_0.html) would be great, and hard-coding the 8 new request parameters and `id_token` response parameter might not be ideal (especially if there end up being conflicting standards in the future).

**Comment by alexcrichton** [comment]
@ramosbugs sorry I don't quite have time any more to maintain this library, but if you'd like to pick it up I'd be more than willing to add you and/or transfer it!

**Comment by ramosbugs** [comment]
Sure, if you wouldn't mind adding me, that would be great! I'd rather add OIDC functionality to this lib so others can use it, rather than building everything from scratch just for my use case. I don't see a need to transfer the whole repo though (at least at this point).

Who would be the best person to review these changes? Even if I have merge access, it would probably be best for someone else to take a look at major changes.

**Comment by ramosbugs** [comment]
Added a generic `extensions` field here in a way that (I believe) maintains backward compatibility: https://github.com/ramosbugs/oauth2-rs/commit/89ce2158f83114e40be9df3b26b6efab38e2178f

Still need to add some new tests before sending a PR.

**Comment by alexcrichton** [comment]
Ok I've invited you! Unfortunately there's not many reviewers right now :(

**Comment by andor44** [comment]
Serde's new [flatten](https://serde.rs/attr-flatten.html#capture-additional-fields) feature could be very useful here.

**Comment by ramosbugs** [comment]
Cool, thanks for the pointer! I've been chatting with @insanitybit, and he suggested using a trait-based approach to support future extensibility in a way that won't require breaking backward compatibility (after a one-time breaking change for 2.0.0). He made a good point that adding a new field to a public struct is a breaking change since all instantiations of that struct outside of the library break. My WIP branch is here: https://github.com/ramosbugs/oauth2-rs/tree/token_ext_trait

The implementation is somewhat more complex, but the client code is mostly unchanged (except that it invokes the getters instead of directly accessing the struct fields).

**Comment by ramosbugs** [comment]
The `flatten` feature worked great for the test extension in https://github.com/ramosbugs/oauth2-rs/blob/token_ext_trait/tests/lib.rs#L709! Thanks again for the tip.

**Comment by tac-tics** [comment]
Just a ping on this. I'm trying to integrate with Reddit's OAuth API using this crate. I'm not sure if it's vendor-specific or part of the spec, but I found that I need to pass an additional "duration" parameter during authorization. So this feature would be helpful to me as well. 

I would be more than happy to offer my time to add this feature.

**Comment by ramosbugs** [comment]
#35 should provide the ability to support new response parameters (see `ColorfulToken` in https://github.com/ramosbugs/oauth2-rs/blob/token_ext_trait/tests/lib.rs), but we'll need a way to add additional request parameters. A straightforward option would be to add a function:
```
    fn exchange_code_ext<'a, 'b: 'a>(
        &'b self,
        code: String,
        mut extra_params: Vec<(&'b str, &'a str)>
    ) -> Result<T, RequestTokenError<TE>> {
```
this would mirror the behavior of `exchange_code` but accept additional parameters to be passed alongside the request. if that works for you, I'd welcome it as a follow-on to #35.

**Comment by ramosbugs** [comment]
Whoops, didn't mean to close since only the arbitrary response parameters are currently supported, not the request parameters.

**Comment by NilSet** [comment]
Will there be a 2.0 release once this supports arbitrary request params?

**Comment by ramosbugs** [comment]
I may cut a 2.0 release without this change, since I think it can be added later without breaking backward compatibility. Separately, I'm working on an OpenID Connect crate built on top of this crate, which serves as a way to verify that the extensibility in the 2.0 release is sufficient to build those types of extensions. I'd like to avoid freezing the 2.x interface until that crate is mostly done, but I can cut a 2.0-alpha release at any time if that would be useful to you. I think any breaking changes at this point would likely be minor, if any. Thoughts?

**Comment by jtescher** [comment]
@ramosbugs 2.0-alpha branch release would be great for testing 🙏

**Comment by ramosbugs** [comment]
Done! https://crates.io/crates/oauth2/2.0.0-alpha.1

Please file issues (or send PRs) for anything you find or would like to see improved.

**Comment by jtescher** [comment]
@ramosbugs alpha.1 working really well so far! Mind cutting an alpha.2 to get the new changes in?

**Comment by ramosbugs** [comment]
Done.

Also, https://github.com/ramosbugs/openidconnect-rs is starting to approach feature completeness, so I'm gaining confidence that this crate's API will remain stable

**Comment by jongiddy** [comment]
Implementation of [Proof Key for Code Exchange](https://tools.ietf.org/html/rfc7636) requires additional parameters in both the Authorization Code request and the Access Token request. Currently, it's possible to call `authorize_url_extension` (in 2.0.0-alpha-2) to pass additional parameters to the Authorization Code request, but it is not possible to pass additional parameters to the `exchange_code` request.

**Comment by jongiddy** [comment]
Well, since I had thought of implementing it, https://github.com/ramosbugs/oauth2-rs/pull/43 adds PKCE to the client.

As further extensions are required for methods that encapsulate more logic, users requiring the `extension` methods will need to reimplement that logic themselves. Have you considered adding a `extra_params: &[(&str, &str)]` parameter to the standard methods? With a constant `&[()]` for the simple cases?

**Comment by ramosbugs** [comment]
With #43 merged, I think we can close this issue now.
