### ISSUE TITLE
Implement SecretType::into_secret

### ISSUE THREAD

**Issue by IvanUkhov** [ramosbugs/oauth2-rs#271]
It would be helpful to have a method to get the ownership of the underlying string back. What do you think?

**Comment by ramosbugs** [comment]
Hey @IvanUkhov,

This sounds reasonable. The Rust idiom I often see is an accessor method called `inner()` that returns a reference and another method called `into_inner()` that takes ownership and returns the inner value. Since the secret types currently have an accessor called `secret()`, it would probably make sense to call the new method `into_secret()` instead of implementing the `From` trait. This naming also helps remind callers that they're dealing with a sensitive value they should be careful with, which may help keep these secrets out of logs or other undesirable sinks.

**Comment by IvanUkhov** [comment]
Clear. Done in #272.
