### ISSUE TITLE
Inconsistent `IssuerUrl` construction

### ISSUE THREAD

**Issue by gibbz00** [ramosbugs/oauth2-rs#277]
```rust
let socket_address = "http://127.0.0.1:3000";
let issuer_url_0 = IssuerUrl::new(socket_address.to_string()).unwrap();
let issuer_url_1 = IssuerUrl::from_url(socket_address.parse::<Url>().unwrap());
assert_eq!(issuer_url_0, issuer_url_1);
```

```
assertion `left == right` failed
  left: IssuerUrl("http://127.0.0.1:3000")
  right: IssuerUrl("http://127.0.0.1:3000/")
```

**Comment by ramosbugs** [comment]
Hey @gibbz00, this is intentional behavior. Parsing the string to a `Url` (using the `url` crate) performs canonicalization, but the [spec](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) requires exact string comparisons of issuer URLs without any canonicalization:
> The Issuer Identifier for the OpenID Provider (which is typically obtained during Discovery) MUST exactly match the value of the iss (issuer) Claim.

The `from_url` constructor is provided for convenience but shouldn't be used if the issuer URL isn't already canonical.

**Comment by ramosbugs** [comment]
Here's an explanatory comment: https://github.com/ramosbugs/openidconnect-rs/blob/fd404985ef6c8e546f951191f4e1bc791615f5ca/src/macros.rs#L275-L284

**Comment by gibbz00** [comment]
Hi, thanks for the quick reply.

I did see the comment before, but your explanation clarified some of my remaining questions 😊

I was thinking that maybe a URI could be used internally instead? URIs do distinguish paths ending in `/` with those who don't.  I think this would eliminate some confusion/bugs that are hard to track down. It would also make `RedirectUrl` slightly more correct, as it should be a URI and not a URL after all.

(I've had good experiences with [`fluent_uri`](https://github.com/yescallop/fluent-uri-rs) if that's an approach worth looking into.)

**Comment by ramosbugs** [comment]
I think you're technically correct, though I'm unclear on which *absolute* URIs (which redirect URIs have to be) aren't also URLs. Since to date no one has filed an issue with a use case requiring non-URL URIs, I think I'd prefer not to make such significant breaking changes at this point. If clear use cases arise, I'd be happy to revisit the topic.
