### ISSUE TITLE
[5.00.alpha4] device code workflow expects interval to be returned from server

### ISSUE THREAD

**Issue by ronnybremer** [ramosbugs/oauth2-rs#278]
When initiating a device code workflow against an OAuth2 server, the interval in the authorize request is optional according to https://www.rfc-editor.org/rfc/rfc8628#section-3.2

However, when not returned I am facing this error:
```
Failed to get device code: Parse(Error { path: Path { segments: [Map { key: "interval" }] }, original: Error("invalid type: null, expected u64", line: 1, column: 218) }
```

The source code provides a serde default, but somehow that doesn't seem to work. What am I doing wrong?

**Comment by ramosbugs** [comment]
I think the issue here is that `interval` is being provided and set to `null`, rather than simply omitted. If it were omitted, the serde default would be used, but since it's provided and `null` (not the expected u64 type), it fails. The spec isn't clear about whether `null` is permitted, but I think it's reasonable to fix this and treat it as if the field were omitted (which is how serde treats all of the `Option` fields).

**Comment by ronnybremer** [comment]
Thank you for your insight @ramosbugs, this is indeed the root cause. The spec says "OPTIONAL" which I guess can be interpreted either way, being omitted or NULLed.
