### ISSUE TITLE
Tweaking existing extra fields require clone

### ISSUE THREAD

**Issue by pickfire** [ramosbugs/oauth2-rs#284]
I want to add `expires_at` in extra_fields so that I know when it expires, but it requires cloning each field, since there are no option for me to get the original raw values from the `StandardTokenResponse`.

```rust
use oauth2::basic::{BasicClient, BasicTokenType};
use oauth2::{
    reqwest, AccessToken, EndpointNotSet, EndpointSet, ExtraTokenFields, PkceCodeVerifier,
    StandardTokenResponse, TokenResponse,
};
use oauth2::{
    AuthUrl, AuthorizationCode, ClientId, ClientSecret, CsrfToken, PkceCodeChallenge, RedirectUrl,
    RevocationUrl, Scope, TokenUrl,
};

#[derive(Clone, Debug, Serialize, Deserialize)]
struct TimeExtraTokenFields {
    expires_at: Option<DateTime<Utc>>,
}

impl ExtraTokenFields for TimeExtraTokenFields {}

let expires_at = &token_response.expires_in().map(|d| Utc::now() + d);
let mut new_token_response = StandardTokenResponse::new(
    token_response.access_token().clone(),
    token_response.token_type().clone(),
    TimeExtraTokenFields { expires_at },
);
new_token_response.set_expires_in(token_response.expires_in().as_ref());
new_token_response.set_refresh_token(token.refresh_token().cloned());
new_token_response.set_scopes(token_response.scopes().cloned());
```

Can we have something like `into_raw_parts` to take those stuff out and modify it? Or have an option to change the extra fields?

**Comment by ramosbugs** [comment]
does [`StandardTokenResponse::set_extra_fields`](https://docs.rs/oauth2/latest/oauth2/struct.StandardTokenResponse.html#method.set_extra_fields) do what you need?

**Comment by pickfire** [comment]
No, because the type changed to `TimeExtraTokenFields` from `EmptyTokenFields`.

**Comment by ramosbugs** [comment]
Ah, I see. It sounds like you're trying to go from an existing `StandardTokenResponse<EmptyTokenFields, _>` to a `StandardTokenResponse<TimeExtraTokenFields, _>`.

Can you instantiate the original one using `TimeExtraTokenFields` (with `expires_at: None`)  to avoid the need to change the `StandardTokenResponse`'s `EF` generic type?

I'd be potentially open to adding a `.map_extra_fields()` method to allow transformations of the `EF` type, but I'd like to understand the use case first.

**Comment by ramosbugs** [comment]
Btw, the standard token response already includes an [`expires_in`](https://docs.rs/oauth2/latest/oauth2/struct.StandardTokenResponse.html#method.expires_in) field. Adding a duplicate with that name to the extra fields will cause problems if you try to serialize or deserialize the type. There's also a [`set_expires_in`](https://docs.rs/oauth2/latest/oauth2/struct.StandardTokenResponse.html#method.set_expires_in) method for modifying it.

**Comment by ramosbugs** [comment]
> I'd be potentially open to adding a `.map_extra_fields()` method to allow transformations of the `EF` type, but I'd like to understand the use case first.

Looking at the code snippet above again, it seems like the use case is to bridge the gap between `expires_in`, which is a duration from the current time, and `expires_at`, which is an absolute time. My suggestion is not to use the `StandardTokenResponse` as a container to store and pass around for other purposes. It's designed to represent the server's response, and nothing else. I would copy the desired fields (`access_token`, etc.) to some other data structure of your choosing alongside any other auxiliary information that you need to accompany it (such as an expiration timestamp).

This crate is intended as a low-level Rust representation of the relevant OAuth2 RFCs, rather than a high-level authentication library that provides an end-to-end auth solution for specific types of apps (which could be built on top of this library). Consequently, I don't think it makes sense to add `.map_extra_fields()` for this use case.
