### ISSUE TITLE
redundant error in 5.0.0-rc.1

### ISSUE THREAD

**Issue by ahl** [ramosbugs/oauth2-rs#288]
If, say, I give an invalid URL to code like this:

```rust
        let auth_client = BasicClient::new(ClientId::new(client_id.to_string()))
            .set_auth_uri(AuthUrl::new(format!("{}authorize", &self.host))?)
            .set_token_uri(TokenUrl::new(format!("{}device/token", &self.host))?)
            .set_auth_type(AuthType::RequestBody)
            .set_device_authorization_url(device_auth_url);

        let details: StandardDeviceAuthorizationResponse = auth_client
            .exchange_device_code()
            .request_async(client)
            .await?;
```

I'll see an error like this:

```
Request failed: request failed: error sending request for url ...
```

It might be nice to just see "request failed" once. In this case I'm using an `reqwest` client so I see that we're hitting this code:

```rust
/// Error encountered while requesting access token.
#[derive(Debug, thiserror::Error)]
pub enum RequestTokenError<RE, T>
where
    RE: Error + 'static,
    T: ErrorResponse + 'static,
{
    /// An error occurred while sending the request or receiving the response (e.g., network
    /// connectivity failed).
    #[error("Request failed")]
    Request(#[from] RE),
}

pub enum HttpClientError<RE>
where
    RE: Error + 'static,
{
    /// Error returned by reqwest crate.
    #[error("request failed")]
    Reqwest(#[from] Box<RE>),
}
```

Would it be possible to let `RequestTokenError`'s `RE` be responsible for the error message to avoid the redundancy?

Thanks! And thanks for this crate!

**Comment by ramosbugs** [comment]
Hey @ahl,

Thanks for reporting this issue! This made me realize I shouldn't have left the enum variant with the name `Reqwest` since it's used by all of the HTTP clients, including the non-reqwest ones. Unfortunately, I just stabilized the API for 5.0, so that ship has sailed until 6.x. 🤦‍♂️ 

As for the error message, I'm thinking it would make sense to change `request failed` in `HttpClientError` to `client error`. This would change the error message to `Request failed: client error: error sending request for url ...`. This approach would distinguish errors returned by the HTTP client library from the other sources of fallibility introduced in 5.0 with the move to `http::{Request, Response}` types for the HTTP client interface (see [upgrade guide](https://github.com/ramosbugs/oauth2-rs/blob/main/UPGRADE.md#use-httprequest-response-for-custom-http-clients)). Would that work for you?

**Comment by ahl** [comment]
Yep! Sounds good. Thanks
