### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by thedrow** [ramosbugs/oauth2-rs#44]
Currently this library uses curl to perform HTTP requests.
It'd be nice if we could add an async API that supports the tokio event loop.
I'm not sure if it's possible with the curl bindings but it will allow us to use the async/await syntax in the future.

**Comment by ramosbugs** [comment]
Thanks for the suggestion! I would definitely be interested in adding async support to this library, but I probably won't have the bandwidth to implement these changes any time soon. I would happily review any contributions toward this effort, however.

As far as continuing to use curl, that's not a strict requirement if there are more tokio-friendly HTTP clients that still provide reasonable security guarantees (e.g., TLS cert validation). I haven't looked into other Rust HTTP clients at all.

**Comment by thedrow** [comment]
Reqwest (https://docs.rs/reqwest/0.9.2/reqwest/) seems pretty popular. It also has an async API.

**Comment by ramosbugs** [comment]
I continue to agree with the goals of supporting an async API and different (non-curl) HTTP backends. However, it doesn't look like we're close to merging those features in, so I'm going to go ahead and promote the current master branch to 2.0.0-beta.1 and avoid any additional breaking changes on the 2.x major release.

We can still merge these new features in as soon as they're ready in preparation for a breaking 3.x release.

**Comment by udoprog** [comment]
I have an async branch of this library here (backed by reqwest):
https://github.com/udoprog/oauth2-rs/tree/async

I'm using it in one of my projects here:
https://github.com/udoprog/setmod/blob/master/bot/src/oauth2.rs#L420

The biggest difference is that setting up a request returns a request builder to reduce the amount of parameterization needed. Instead, you specify the expected response type during a separate `execute()` function which returns a future:
https://github.com/udoprog/setmod/blob/master/bot/src/oauth2.rs#L139

My project includes examples for interacting with Twitch, YouTube, and Spotify. Each of with their own quirks.

If you're interested in moving towards something like this in `3.x`, I would be happy to clean up the patches and send a PR.

**Comment by ramosbugs** [comment]
Thanks, I'll take a look in the next week or so!

**Comment by ramosbugs** [comment]
I'm working on porting over @udoprog's changes but with some alterations, such as:
- not relying on nightly features like async await (this crate needs to work on stable, though I'm not opposed to some nightly-only features gated by feature flags)
- abstracting away the HTTP implementation so that other backends can be plugged in (I'll probably make Reqwest the new default, and include curl as an alternative behind a feature flag)
- moving to a builder pattern for both the authorization request and token request

**Comment by udoprog** [comment]
Awesome! I'm glad to see this moving. My branch was somewhat hastily thrown together to get it working.

FWIW, the `async` branch currently doesn't use any nightly features. Only the project I'm using the branch in does.

**Comment by ramosbugs** [comment]
the latest master (e45724de3994df5c81a0155cfb050331ff9b33f5) now has a builder-pattern-based API for both the authorization URL and token exchange requests. the `request` method for each token exchange takes an arbitrary HTTP client, so the library is no longer tied exclusively to `curl`. the examples and docs are updated to reflect the new API.

please let me know if you have comments about the new API, and feel free to open separate issues.

I'll now start working on adding a `request_async` method for each token exchange struct that takes an asynchronous `http_client` function (which returns a `Future`), and I'll include a reqwest-based implementation of this `http_client` interface.

Having both the `curl` and `reqwest` crates as default dependencies makes this library a bit too heavyweight, so I'll likely introduce feature flags for toggling these (with `reqwest` the likely default in 3.x).

**Comment by ramosbugs** [comment]
398d3a274948c19bed918cf7f3f71515640e712d now includes the async API (see [this example](https://github.com/ramosbugs/oauth2-rs/blob/47e93d79a936efb0d168d698a7ba1ea5be686ea9/src/lib.rs#L85))

**Comment by ramosbugs** [comment]
Turns out using reqwest in its default configuration causes an SSRF vulnerability: https://github.com/ramosbugs/oauth2-rs/releases/tag/3.0.0-alpha.2

**Comment by udoprog** [comment]
@ramosbugs I looked through the updated crate now.

So I'm wondering if you would consider two things:

Make curl/reqwest optional dependencies depending on which one you want to use.

Remove generic parameters from `Client` in favor of having them only on the `request` function. The things that need to be generic is the token response and possibly the corresponding error type. But the current approach forces users to propagate three generic parameters across their application. This proved to be rather challenging for me to use when building an async module that can talk to multiple oauth2 providers at once, persist tokens, and handle refreshes.

I'd be happy to contribute to any of these as long as you're OK with it.

**Comment by ramosbugs** [comment]
> Make curl/reqwest optional dependencies depending on which one you want to use.

Definitely support this, and would welcome a PR that puts them behind Cargo feature flags. We probably want one of them to be enabled by default (maybe reqwest?) so that it doesn't require any feature flags to use the crate out of the box.

> Remove generic parameters from Client in favor of having them only on the request function.

I thought about this as I was refactoring the library. The reason I decided to leave the type parameters on the `Client` struct rather than the `request` method is that the former allows the use of type aliases. For most users of the crate, `BasicClient` probably suffices, meaning that they don't have to propagate any types around at all. If the types are defined on the `request` method, then explicit types need to be specified at each call site, and I don't think there's a way to use type aliases to avoid this. I'd prefer to keep the common case simple for users of the library, even if it means more advanced cases require additional type plumbing.

**Comment by udoprog** [comment]
> I'd prefer to keep the common case simple for users of the library, even if it means more advanced cases require additional type plumbing.

I'd like to emphasize that the sheer _amount_ of plumbing is arduous. When we want to keep simple things simple, we don't want to use it at the expense of making hard things virtually impossible. Right now you have to copy every type constraint imposed by the library and propagate these parameters all over your code to be able to pass a `Client` instance around.

Before committing to a decision on this I'd urge you try and build a client that talks to Twitch as an exercise and include it as an example since it can't use `BasicClient`. Or build one that uses generic code to talk to multiple incompatible providers at once (like Twitch + Google). Type aliases don't work in these cases.

**Comment by udoprog** [comment]
To clarify, the approach I took in my branch was to use a single trait with associated types. The request would then look like this for basic tokens:

```rust
let client = /*...*/;
let token = client.execute_async::<BasicFlow>()
```

**Comment by ramosbugs** [comment]
I work on a codebase that uses this crate to interface with a few different flavors of OAuth providers, and the plumbing didn't seem too extensive or difficult. That use case involves various extensions on top of baseline OAuth2, which are easily handled by using wrapper types around `oauth2::Client` that hide the underlying generic types. Composing multiple clients of different types seems to be beyond the scope of this crate and something best handled at a higher layer of abstraction.

The generic types get significantly more complicated in the [openidconnect crate](https://github.com/ramosbugs/openidconnect-rs) (built on top of this crate), and there are quite a few methods there that would require explicit types at every call site if we were to take this other approach. By contrast, providing the types at instantiation time simplifies the other call sites and also ensures that the different methods return consistent parameterized types (since some of the type parameters affect multiple methods).

**Comment by udoprog** [comment]
> I work on a codebase that uses this crate to interface with a few different flavors of OAuth providers, and the plumbing didn't seem too extensive or difficult.

Do you have a link? It was a real pain in the project I was working on. I didn't use wrappers however, but it also seems like a lot of repeated work for projects to wrap all the client variations they have.

> The generic types get significantly more complicated in the openidconnect crate (built on top of this crate), and there are quite a few methods there that would require explicit types at every call site if we were to take this other approach.

I checked out the project, and I'm curious how you'd embed a [type like this] in a wrapper? That's definitely a case I'd suggest switching to a single trait with associated types instead. Obviously more parameters than in this crate though. Even so, switching to a single parameter on `Client` that uses associated types would help reduce boilerplate a lot.

[type like this]: https://github.com/ramosbugs/openidconnect-rs/blob/master/src/lib.rs#L150

**Comment by ramosbugs** [comment]
> Do you have a link?

Unfortunately, it's a closed source project owned by my employer.

> I'm curious how you'd embed a type like this in a wrapper?

Wrappers can take the form:
```
struct OpenIdClient<OneOrTwoParameterizedTypes> {
    inner: openidconnect::Client<MostOfTheTypes..., OneOrTwoParameterizedTypes>
}
impl<OneOrTwoParameterizedTypes> OpenIdClient<OneOrTwoParameterizedTypes> {
  pub fn new(...) {...}
  pub fn authorize_url(...) {...}
  pub fn exchange_code(...) {...}
}
```
Since a given user of the library is probably only using a subset of the library's functionality, the wrapper type doesn't need to define everything that's in the library; just the subset that's used. If you need multiple wrapper types (e.g., to support very different OAuth providers like Twitch and Google), one can easily define a trait and have each of the wrapper types implement that trait.

I don't think wrapper types are needed for simple use cases of either of these crates, but they can simplify the more advanced use cases.

> switching to a single parameter on Client that uses associated types would help reduce boilerplate a lot.

This doesn't seem like the intended purpose of associated types (or traits). Passing in a trait as the single type parameter doesn't really make sense to me because for a given trait and specific set of associated types, there won't be more than one struct that implements that trait (i.e., it's not actually functioning as a trait/interface). If the goal is to reduce boilerplate rather than provide multiple implementations of a trait, maybe a macro makes more sense.

**Comment by udoprog** [comment]
> This doesn't seem like the intended purpose of associated types (or traits). Passing in a trait as the single type parameter doesn't really make sense to me because for a given trait and specific set of associated types, there won't be more than one struct that implements that trait (i.e., it's not actually functioning as a trait/interface). If the goal is to reduce boilerplate rather than provide multiple implementations of a trait, maybe a macro makes more sense.

It is true that there won't be more than one struct per implementation, but the struct can be just as generic as the client if it wants to.

I took a couple of minutes of porting your crate to use a `Config` trait here with associated types:
https://github.com/udoprog/oauth2-rs/commit/18ebe0bfd7586696fea01ed71695f4a42d4cf28a

`BasicClient` is a type alias like this:

```rust
pub type BasicClient = Client<Basic>;
```

If you want to build a partially specialized `Config` struct, you could do something like this:

```rust
struct SomePartialConfig<TR>(PhantomData<TR>);

impl<TR> Config for SomePartialConfig<TR> where TR: TokenResponse {
    type TokenResponse = TR;
    type ErrorResponse = crate::basic::BasicErrorResponse;
}
```

Which is used like this:

```rust
type SomeWeirdClient = Client<SomePartialConfig<MyTokenResponse>>;
```

The big difference however, is that any receiver of Client that used to look like this:

```rust
fn takes_client(client: &Client<TE, TR, TT>)
where
    TE: ErrorResponse,
    TR: TokenResponse<TT>,
    TT: TokenType,
{
    /*  */
}
```

Can now be written like this:

```rust
fn takes_client(client: &Client<T>)
where
    T: Config
{
    /*  */
}
```

Or like this if you want to use impl traits:

```rust
fn takes_client(client: &Client<impl Config>) {
    /*  */
}
```

**Comment by ramosbugs** [comment]
In the `Contains` example from Rust by Example, `Contains` itself is a true trait that one would expect to have multiple implementations. In that circumstance, I agree that associated types can be useful. This would potentially be an argument for making `TT` an associated type within `TokenResponse`, rather than parameterizing it.

I still don't agree that `Config` here is the same use case for which associated types are intended.

Using an even simpler wrapper type where `inner` is public should involve a similar amount of code as using a `Config` trait (possibly less):
```
struct MyClient<T> {
  pub inner: oauth2::Client<BasicErrorResponse, StandardTokenResponse<T>, T>,
}
```
this similarly provides a partial specialization that can be passed around with a single type parameter.

**Comment by udoprog** [comment]
> I still don't agree that Config here is the same use case for which associated types are intended.

Why? This is the circumstance they are designed for. Reduce the number of generic parameters by associating them with other parameters. Besides that, it seems to satisfy your expressed needs while not forcing me to add potentially hundreds of lines of boilerplate to my project. You'd probably also set a dramatic reduction in boilerplate of you adopted this pattern in your projects.

> this similarly provides a partial specialization that can be passed around with a single type parameter.

To be clear, I presented partial specialization because you expressed a use for it earlier. I don't have one.

**Comment by ramosbugs** [comment]
Again, associated types are for traits; traits are for things that may have multiple implementations. There's no conceivable situation in which there will be multiple structs implementing `Config` with the same set of associate types. This is in contrast to, e.g., `Future`, where there may be many futures that return a given pair of `Item`/`Error` types.

The mechanism intended for hiding type parameters with structs is type aliases, which even support the partial specialization case illustrated above (I forgot about this when I suggested wrapper types for that case). [`std::io::Result`](https://doc.rust-lang.org/1.1.0/std/io/type.Result.html) is an example.

I appreciate the feedback and the discussion we've had here, but I'm convinced that using a trait here would be a misuse of traits, and I've used the crate enough to believe that these different use cases can be handled without hundreds of lines of boilerplate.

**Comment by udoprog** [comment]
> There's no conceivable situation in which there will be multiple structs implementing Config with the same set of associate types.

Ah. I think you've misunderstood. The point is that I can take the trait and build an implementation for non basic providers. Like:

```rust
struct TwitchConfig;

impl Config for TwitchConfig {
    type TokenResponse = TwitchTokenResponse;
    type ErrorResponse = BasicErrorResponse;
}

let Client twitchClient = Client::<TwitchConfig>::new();
```

There will be one implementation for every incompatible OAuth 2.0 provider. Not just a single one.

**Comment by ramosbugs** [comment]
No, my point is that the specialization `Config<TokenResponse=TwitchTokenResponse, ErrorResponse=BasicErrorResponse>` is itself a trait, and there can be many impls for that set of associated types.

Given:
```
struct Config1;
impl Config for Config1 {
  type TokenResponse = TwitchTokenResponse;
  type ErrorResponse = BasicErrorResponse;
}

struct Config2;
impl Config for Config2 {
  type TokenResponse = TwitchTokenResponse;
  type ErrorResponse = BasicErrorResponse;
}
```

The types `Client<Config1>` and `Client<Config2>` are distinct non-interchangeable types in Rust. This would be fine if there were actually a reason to have multiple implementations of `Config<TokenResponse=TwitchTokenResponse, ErrorResponse=BasicErrorResponse>`, but there isn't. Using associated types in this way is not correct and has undesirable side effects in the Rust type system. `Client<TwitchTokenResponse, BasicErrorResponse>` avoids these issues, and the boilerplate can be hidden using the ways I've suggested above. Consequently, I won't be removing the generics from this crate.

**Comment by s-panferov** [comment]
Is something preventing from adding `request_async` method to [`RefreshTokenRequest`](https://docs.rs/oauth2/3.0.0-alpha.2/oauth2/struct.RefreshTokenRequest.html) as well?

**Comment by ramosbugs** [comment]
I think I initially forgot to do that, but the current master has it: https://github.com/ramosbugs/oauth2-rs/blob/da0b8ffb17251eded8ca5de38acb73fff54ee099/src/lib.rs#L994

I'll cut a 3.0.0-alpha.3 release now to push it to crates.io

**Comment by ramosbugs** [comment]
https://crates.io/crates/oauth2/3.0.0-alpha.3 is pushed.

I'm going to go ahead and close this issue. Feel free to open new issues for anything else you find!
