### ISSUE TITLE
Smaller version without reqwest

### ISSUE THREAD

**Issue by nhellwig** [ramosbugs/oauth2-rs#77]
Hi,

first of all thanks a lot for this crate. I do find the way to actually using your custom http-client implementation really great. Nevertheless this comes with a lot of "bloat" for tokio, reqwest, hyper etc. Not sure if this is actually needed, when you provide your own. This could also be me missing better insight into the implementation.

Cheers,
Niko

**Comment by ramosbugs** [comment]
Hi Niko,

Specifying `default-features = false` on the crate import should remove `reqwest` and its dependencies. Similarly, not specifying `futures-01` or `futures-03` will remove all of the async dependencies. The one combination the crate doesn't currently support is `futures-03` without `reqwest` due to limitations in Cargo.toml's format (i.e., not supporting `#[cfg(all(feature = "reqwest", feature = "futures-03"))]` during dependency computation).

Does that answer your question, or are you still experiencing excessive bloat even without the default features (`reqwest`) enabled?

**Comment by nhellwig** [comment]
Hi,

thanks a lot for your answer. Yeah I'm using future-03. Needed the async stuff because I wrote an implementation for the surf crate. Was using surf already. That's why I wanted to avoid using so many different crates. I get your point.
Do you see a way of solving this? I also get my thinking on it.

Cheers

**Comment by vorot93** [comment]
I think it would be a shame if this crate bundled a full-featured HTTP client instead of a light wrapper. Reqwest is just fine.

**Comment by ramosbugs** [comment]
For ease of use, my original goal was for the feature flags to work as follows:
- `reqwest` = `reqwest 0.9`
- `reqwest` + `futures-01` = `reqwest 0.9`
- `reqwest` + `futures-03` = `reqwest 0.10`
- `default-features = false` + `futures-01` = no `reqwest` dependency
- `default-features = false` + `futures-03` = no `reqwest` dependency

Unfortunately, there's no way to specify that in `Cargo.toml`, which led to the current functionality. At the time, that seemed preferable to exposing `reqwest-09` and `reqwest-010` as separate feature flags.

However, I'm sympathetic to a desire to avoid code bloat and slower compilation time, so I'm thinking the best way forward is to introduce separate `reqwest-09` and `reqwest-010` feature flags, and to make up for the additional complexity with better docs. I'll try to get around to that in the next week or so, though I'd also welcome a PR if anyone wants it sooner.

**Comment by ramosbugs** [comment]
The latest version now supports async/await without `reqwest`: https://crates.io/crates/oauth2/3.0.0-alpha.7. See updated docs here: https://docs.rs/oauth2/3.0.0-alpha.7/oauth2/

**Comment by nhellwig** [comment]
nice! thanks a lot!
