### ISSUE TITLE
Type error in Access Token Response if expires_in is string

### ISSUE THREAD

**Issue by ralpha** [ramosbugs/oauth2-rs#85]
When a server returns an Access Token Response with expires_in as a string instead of an integer (u64) this will give an error as follows:
Err(Parse(Error("invalid type: string \"600\", expected u64", line: 1, column: 737), [....]))

Expected right now:
```
{
    "access_token": "<redacted>",
    "token_type": "Bearer",
    "expires_in": 600,
    "refresh_token": "<redacted>"
}
```
Error if given:
```
{
    "access_token": "<redacted>",
    "token_type": "Bearer",
    "expires_in": "600",
    "refresh_token": "<redacted>"
}
```

I know https://tools.ietf.org/html/rfc6749#section-4.1.4 shows an integer, not a string.
and rfc6749 section 5.1 notes:
> Parameter names and string values are included as JSON strings.
> Numerical values are included as JSON numbers.  The order of
> parameters does not matter and can vary.

So this is technically not a bug or unexpected behavior. But I'll still report this information. 
This issue can be closed if building in a check is not considered.

**Comment by ramosbugs** [comment]
As you cited from the spec, the value is supposed to be a JSON number and not a string, so a parse error is the expected result of the server returning an invalid token response. Clients wishing to interoperate with non-compliant servers can define their own [`TokenResponse`](https://docs.rs/oauth2/3.0.0-alpha.9/oauth2/trait.TokenResponse.html) implementation instead of using [`StandardTokenResponse`](https://docs.rs/oauth2/3.0.0-alpha.9/oauth2/struct.StandardTokenResponse.html).
