### ISSUE TITLE
Scopes not parsing

### ISSUE THREAD

**Issue by beemstream** [ramosbugs/oauth2-rs#86]
Hi, been trying to get BasicClient to work with this kind of response:
```
{
  "access_token": "<redacted>",
  "expires_in": 14487,
  "id_token": "<redacted>",
  "refresh_token": "<redacted>",
  "scope": [
    "openid",
    "user:read:email"
  ],
  "token_type": "bearer"
}
```

And I am getting the following error for `scope` - `Parse(Error("invalid type: sequence, expected a string", line: 1, column: 831...`

Any ideas on how to fix this?

**Comment by ramosbugs** [comment]
per https://tools.ietf.org/html/rfc6749#section-3.3:
```
   The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.  The strings are defined by the
   authorization server.  If the value contains multiple space-delimited
   strings, their order does not matter, and each string adds an
   additional access range to the requested scope.
```
the response above returns an array instead of a space-delimited list, which is not a valid OAuth2 token response.

if you need to interoperate with a non-compliant server, you can define your own struct that implements the `TokenResponse` trait instead of using the `StandardTokenResponse` struct that observes the RFC.

**Comment by beemstream** [comment]
Thanks!
